### ISSUE TITLE
Need vcgencmd full path to work...

### ISSUE THREAD

**Issue by domcars0** [asavah/script.pidisplaypower#1]
Hi,
First thank you very much for this script.
For your information, if I do not put the full vcgencmd full path in the script, it does not work on my OSMC raspberry B+ box, and throw to exception:
16:39:20 T:2837443616  NOTICE: -->Python Interpreter Initialized<--
16:39:20 T:2837443616   ERROR: script.pydisplaypower: Exception running vcgencmd

I need to replace the gui.py line:
cmd = subprocess.Popen(['vcgencmd', 'display_power', arg2], stdout=subprocess.PIPE, st
by  
cmd = subprocess.Popen(['/opt/vc/bin/vcgencmd', 'display_power', arg2], stdout=subprocess.PIPE, st

After this small mod it work like a charm.
Thank you again.

**Comment by asavah** [comment]
Thanks for reporting.
This happens because /opt/vc/bin is not on system or user $PATH.
On my custom OS vcgencmd is in /usr/bin, so I did not run into this issue.
I'll patch in a workaround as soon as I get some spare time.

**Comment by asavah** [comment]
Fixed in d608244
