### ISSUE TITLE
Doesn't seem to actually turn off power

### ISSUE THREAD

**Issue by Vlayke** [asavah/script.pidisplaypower#2]
Hi,

I've downloaded and installed your addon on RaspberryPi, model B where I'm running OpenElec.

I went to the screensaver selection and there in the settings chose the addon and used the "preview" option.
The result was that the screen went black, but the power to the HDMI didn't actually seem to go out. This is evidenced by the fact that my projector (connected to the HDMI) didn't give notice, saying that there is a loss of signal. So it has to be receiving something.

I was hoping that the addon would turn off the HDMI signal, which would eventually cause the projector to shut down.

Please let me know if I'm expecting wrong kind of behavior or if I can provide you with some additional data to help troubleshoot this.

Thanks,
Vlayke

**Comment by asavah** [comment]
See #1 for workaround.
Will fix this as soon as I get some spare time.

**Comment by Vlayke** [comment]
Hi asavah,

I appreciate that you think that the previous workaround helps me in my situation. Unfortunately it doesn't really.

I uninstalled the addon, changed the .py file according to the info from the issue 1, repackaged it into the addon .zip file and then installed the addon again.

The results are the same as they were originally. Screen goes black, but HDMI output still seems to work.

So I submit to you, that this is another issue, or that it requires another solution in my environment and should be, as such, re-opened.

Again, I'm willing to help out with any kind of information that you may find relevant.

Thanks,
Vlayke
