### ISSUE TITLE
Proposal: Option to turn bluetooth off

### ISSUE THREAD

**Issue by swetoast** [asavah/script.pidisplaypower#3]
Just what the topic said if you feel like adding that :)
Add an option to turn bluetooth off

using this addon to turn off my ambilights best addon so far for rpi

**Comment by rellik8821** [comment]
And turn off wifi pls.

**Comment by asavah** [comment]
No plans for bluetooth, wifi or making you a coffee, sorry.
this is just a dumb screensaver which turns the display off.
