### ISSUE TITLE
Doesn't work on RPI4

### ISSUE THREAD

**Issue by Janghou** [asavah/script.pidisplaypower#4]
vcgencmd display_power doesn't work *yet* on the RPI4

https://github.com/raspberrypi/firmware/issues/1224

**Comment by asavah** [comment]
AFAIK Kodi on PI4 will not use firmware driver at all and will be running on gbm via mesa vc4/v3d driver, thus Kodi should be using standard linux dpms stuff and not vcgencmd hack. Which makes this plugin totally unnecessary.

I don't have my pi4 yet (its on its way) and can not confirm/deny this assumption yet.

**Comment by Janghou** [comment]
Then I guess that dpms stuff isn't working yet on a RPI4. Didn't work with default blank screensaver.

Thx, I used your plugin on my RPI3(+)l, and still using a hacked version on my RPI4  with tvservice -o, tvservice -p, that is somewhat working, tvservice -p has to be issued with ssh (connectBot), that is a small price to pay for saving energy.

**Comment by Janghou** [comment]
BTW it does work now (after updating) on my RPI4 with Kodi.
